sky:
  datasource:
    driver-class-name: 
    host: 
    port: 
    database: 
    username: 
    password: 
  alioss:
    endpoint: 
    access-key-id: 
    access-key-secret: 
    bucket-name: 
  redis:
    host: 
    post: 
    database: 
  wechat:
    appid: 
    secret: 
  shop:
    address: 
  baidu:
    ak: 
