sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tE31yZJTRfPLw8mb79z
    access-key-secret: fAAkilyJVvDYw2qQH9ehd2YTvgSK3p
    bucket-name: sky-itcast-heiye
  redis:
    host: localhost
    post: 6379
    database: 10
  wechat:
    appid: wxbcd5873854332278
    secret: 0f925c66b3fa180a09a9a6493b003659
  shop:
    address: 广东省广州市增城区增城宾馆
  baidu:
    ak: TTpmd7hcEkxQVPcLYoGPlTnCgQk41llf